### ISSUE TITLE
Chrome reloaded when going from My User Access -> User Access and vice versa

### ISSUE THREAD

**Issue by Hyperkid123** [RedHatInsights/insights-chrome#1196]
Maybe just needs to be fixed in the rbac-ui repo?

**Comment by Hyperkid123** [comment]
@john-dupuy these apps have not yet been enabled in the main.yml config. There might be some other changes required. We have one app split into two.

**Comment by Hyperkid123** [comment]
@john-dupuy it is done

**Comment by john-dupuy** [comment]
@Hyperkid123 oh awesome! It's super fast :speedboat:
