### ISSUE TITLE
Login page does not load on ci-beta

### ISSUE THREAD

**Issue by Hyperkid123** [RedHatInsights/insights-chrome#1218]
1) Navigate to ci-beta

Only the masthead loads

**Comment by Hyperkid123** [comment]
This quite a funny issue.
The unauthed page loads locally on `/beta` but not on `/beta/` (trailing slash). We can't load the page on ci without the trailing slash, we get redirected. Hopefully, it will have an easy fix.

**Comment by Hyperkid123** [comment]
@john-dupuy it should be OK now

**Comment by john-dupuy** [comment]
Thanks @Hyperkid123, I can see it is fixed in ci-beta.
