### ISSUE TITLE
Refreshing HCCM OpenShift Charge or Cloud Cost page results in 'File not found'

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#123]
**Describe the bug**
On production if you navigate to either HCCM OCP/AWS cost details; then refresh, the Insights console shows a blank page with 'File not found' text.

**To Reproduce**
1. Go to HCCM OpenShift Charge or Cloud Cost
2. Click on refresh
3. See error

**Expected behavior**
Pages should reload correctly

**Screenshots**
![screen shot 2019-01-24 at 11 24 15 am](https://user-images.githubusercontent.com/17481322/51692856-c5458300-1fcb-11e9-89c1-ce54919c7d15.png)

**Additional context**
This is only an issue with the production environment. I'm not able to reproduce with a local CI or Insights beta.

It was suggested its related to akamai? 

See the kpku-ui issue here: https://github.com/project-koku/koku-ui/issues/429

**Comment by Kinlaw** [comment]
There is a Failover Rule in Akamai that should redirect all requests from /platform/cost-management/* to /platform/cost-management/index.html before hitting NetStorage for the resource. This specific query is not being caught by the rule.

We have an open issue with Akamai to determine/remedy the cause of this.

**Comment by iphands** [comment]
@dlabrecq Is this still an issue on cloud-dot?
I have a regression test suite to help us catch stuff like this and only see things failing on Beta atm.

**Comment by iphands** [comment]
FYI we are using this to help us with the Cloud rules: https://github.com/RedHatInsights/akamai-smoke-test

**Comment by dlabrecq** [comment]
I no longer see the issue on prod. I'll close
