### ISSUE TITLE
Rename Cost Management navigation links

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#138]
Please change the Cost Management "Cloud Cost" and "OpenShift Charge" links, in the left navigation pane, to read "Cloud Details" and "OpenShift Details".

**Comment by chargio** [comment]
@dayleparker Just making sure that these are the proper names to use

**Comment by dayleparker** [comment]
Hi @chargio,
Personally I think "Details" is explicit enough for a navigation pane heading, and the new labels look more consistent than Cost/Charge 👍 

However, is there a reason "Cloud Details" cannot be named something like "AWS Details" or "AWS Cloud Details" or "Cloud Details - AWS" to be more exact, and to parallel "OpenShift Details"?

I may be missing some background here though, as I'm new to the product...

**Comment by nlcwong** [comment]
@chargio & I have talked and we're OK with the following navigation menu name change:
AWS Details replaces Cloud Cost
OpenShift Details replaces OpenShift Charge

**Comment by nlcwong** [comment]
Actually, an amendment to the previous comment, we talked about it more and we would like to make sure that the ORDER of the menu items are as follows:
- Cost Management
-- Overview
-- OpenShift Details
-- AWS Details

**Comment by ryelo** [comment]
Yes, can you make another issue for that? It won't be hard to fix, but easier for tracking.

**Comment by dlabrecq** [comment]
Created https://github.com/RedHatInsights/insights-chrome/issues/151
