### ISSUE TITLE
A11y errors caused by incorrect landmark elements in page structure

### ISSUE THREAD

**Issue by srambach** [RedHatInsights/insights-chrome#1405]
There are multiple `<main>` elements and they are nested, which causes multiple a11y errors related to landmarks.
https://dequeuniversity.com/rules/axe/4.1/landmark-no-duplicate-main?application=AxeChrome

In addition, the "Application Services" app title is not contained with in a landmark.
https://dequeuniversity.com/rules/axe/4.1/region?application=AxeChrome

![image](https://user-images.githubusercontent.com/19825616/117049759-92c67c80-ace2-11eb-8d43-20012b5ea155.png)

@ryelo @karelhala

**Comment by Hyperkid123** [comment]
This may have to wait a bit. This is currently required to suport apps that are not yet migrated to new version of chrome rendering. In fact there is multiple layout updates that need to be done once all services are using the new system.
