### ISSUE TITLE
getToken() returns empty tokens

### ISSUE THREAD

**Issue by petli-openshift** [RedHatInsights/insights-chrome#1451]
We recently observed quite a few empty tokens. This seems to happen within seconds of `Error: Fetching token failed - expired token` events. A quick search points me to this block: https://github.com/RedHatInsights/insights-chrome/blob/bbd212da19149f48ad74704ca60eeaf573f5936a/src/js/jwt/jwt.js#L347-L351

does it make sense to turn that updateToken() on that line? or something else that can handle this more gracefully?
```
  Sentry.captureException(new Error('Fetching token failed - expired token'));
  log('Failed to get encoded token'); 
- updateToken();
+ return updateToken();
```

**Comment by petli-openshift** [comment]
cc @tiwillia@redhat.com

**Comment by ryelo** [comment]
This is actually taken care of in https://github.com/RedHatInsights/insights-chrome/pull/962

**Comment by Hyperkid123** [comment]
I've found a potentially related issue to #962. I think it may be breaking the landing page. When an unauthed user tries to do anything you are immediately redirected to the SSO login.

**Comment by Hyperkid123** [comment]
@ryelo yep, when I remove this line: https://github.com/RedHatInsights/insights-chrome/pull/962/files#diff-cfe5668ee533c9894837c11bdf617c613e727b441082242fd962bb4b56f39ce3R313 the bug is gone. I will remove it for now from the code. Can you take a look again later on?

**Comment by petli-openshift** [comment]
would it make sense to make it configurable? for example,
`ssoExcludes: ['/assets']`
we may see the same issue.

**Comment by ryelo** [comment]
We already have something similar:
https://github.com/RedHatInsights/insights-chrome/blob/4d8a69eeb137e497f7f5cae27d8c0a59769aefcc/src/js/jwt/constants.js#L35

**Comment by Hyperkid123** [comment]
@petli-openshift is this still an issue?

**Comment by petli-openshift** [comment]
I just checked Sentry. There were still a couple of "Fetching token failed - expired token" errors seen from last week, but since no users have reported this, it should've been fixed. thanks for addressing it. I m closing the issue
