### ISSUE TITLE
Reorder Cost Management navigation links

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#151]
The Cost Management would like to make sure that the ORDER of the menu items are as follows:

    Cost Management
    -- Overview
    -- OpenShift Details
    -- AWS Details

**Comment by dlabrecq** [comment]
@ryelo When I run `bash ./scripts/update.sh` for insights-proxy (pulled the latest repo), it says my image is up to date. However, I don't see the recent changes with the Cost management navigation links -- I still see "Cloud Cost" Vs "AWS Details". 

I see the changes in production, but could the image I'm running locally be stale?

**Comment by ryelo** [comment]
@dlabrecq it has nothing to do with the proxy, if you're using `LOCAL_CHROME` then you'll have to pull down the latest master in Chrome.

**Comment by ryelo** [comment]
@dlabrecq if you `git pull` the latest insights-chrome and run `LOCAL_CHROME=true` then you should get the newest version of chrome.

**Comment by dlabrecq** [comment]
I'm just running `docker stop -t 0 insightsproxy > /dev/null ; bash scripts/run.sh`, so not sure where the insights-chrome is coming from?

**Comment by ryelo** [comment]
@dlabrecq Sorry, misunderstanding. We haven't released this version of chrome to stable yet.

**Comment by dlabrecq** [comment]
Ok, that's all I needed to check. Thanks!
