### ISSUE TITLE
Page breaks when clicking manifests link on side nav after manifests page has loaded

### ISSUE THREAD

**Issue by joeldmyers** [RedHatInsights/insights-chrome#1570]
Steps to reproduce: 

1. Navigate to https://console.redhat.com/beta/insights/subscriptions/manifests/
2. Once the page is loaded, click the "manifests" link in the side nav.
3. The page will route to the 'oops page'. This is because the page is trying to render https://console.redhat.com/beta/insights/subscriptions/manifests**/manifests** which ends up rendering the 404 page view.

![Screen Shot 2021-07-29 at 2 22 08 PM](https://user-images.githubusercontent.com/4838984/127553063-ebc458d0-60a6-4776-9577-d5b6f7f67314.png)

<img width="1450" alt="Screen Shot 2021-07-29 at 3 18 01 PM" src="https://user-images.githubusercontent.com/4838984/127552762-be3ec9aa-f5ef-4a79-b091-51290faa0180.png">

**Comment by Hyperkid123** [comment]
@joeldmyers it seems that the `APP_NAVIGATION` listener in the manifests UI is appending an extra segment to the history. I think here is the issue: https://github.com/RedHatInsights/subscription-central-ui/blob/main/src/App.js#L30

THe appID will be deprecated soon. I advise using `event.domEvent.href` which has the full path (without `/beta/`) of the link. Using that and replacing the router basename should work for you.

**Comment by Hyperkid123** [comment]
@joeldmyers seems like the issue was resolved. Feel free to re-open the issue.
