### ISSUE TITLE
keyboard accessibility: Tab iterates over part of left navigation even when hidden

### ISSUE THREAD

**Issue by cben** [RedHatInsights/insights-chrome#1576]
Tab key generally moves top bar (starting at navigation toggle hamburger) -> left navigation -> app content.
- [x] When the left navigation is open, it iterates over all navigation entries, scrolling as necessary :+1:
- [ ] But when it's hidden, it's still iterating over (some of) these entries.  This is not very useful as you can't see the links you're on (except if your browser is showing link URL at the bottom, as in screen recording below).

Ideal behavior is question to UX...  One more useful behavior could be to move the navigation toggle hamburger in Tab order to be _after_ the top bar, right before the navigation links, and skip them when hidden.  Then when not navigating you can keep it closed and only see a single Tab step, and press Space/Enter to open it when needed.
Another idea could be to make left navigation always reachable by Tab, and always shown when so focused — then it may be better to move the whole navigation before top bar, and add some way to skip navigation / skip to content.

There are some more questions about manually open/closed vs automatically due to window width...
(It's tempting to use the same hamburger for "skip navigation links" and "show/hide the bar" goals but should think of 2 auditories — sighted users for whom kbd is just better way to work vs screen reader users.  I don't know enough about the latter.)

### ☑ nav shown
![tab-order-shown-navigation](https://user-images.githubusercontent.com/273688/128850192-6f18a64c-ace1-40c6-866d-38dee2d3decc.gif)

### ☐ nav hidden
![tab-order-hidden-navigation](https://user-images.githubusercontent.com/273688/128850339-284c9bd5-fcd3-4252-a720-2683f21db9a3.gif)

^^ see URLs of the invisible links changing in this corner.  Note it's not all of them, just OCM's own top 4 links.

**Comment by Hyperkid123** [comment]
@cben thanks for reporting the issue. I will go over it probably tomorrow.

**Comment by ryelo** [comment]
Having the hamburger the first thing is a pattern defined by Patternfly. We don't have a "skip to content" so this should be the first thing.

However, when the hamburger is closed, we should not be able tab through any of those items, so yes that is a bug.

**Comment by Hyperkid123** [comment]
> One more useful behavior could be to move the navigation toggle hamburger in Tab order to be after the top bar, right before the navigation links, and skip them when hidden. Then when not navigating you can keep it closed and only see a single Tab step, and press Space/Enter to open it when needed.
Another idea could be to make left navigation always reachable by Tab, and always shown when so focused — then it may be better to move the whole navigation before top bar, and add some way to skip navigation / skip to content.

We have opted to use the default PF behavior. I would suggest creating an issue in their repository to change the page layout behavior.

We will remove the focusing of the nav items if the nav hidden.
