### ISSUE TITLE
Question: what's the suggested strategy to deal with @patternfly versions? 

### ISSUE THREAD

**Issue by riccardo-forina** [RedHatInsights/insights-chrome#1719]
I see versions are not pinned in the package.json, so I checked on the latest main the versions locked in the package-lock and I see this:

```
❯ npm ls @patternfly/patternfly @patternfly/react-core @patternfly/react-table @patternfly/react-icons @patternfly/react-tokens @pattefnly/react-styles
insights-chrome@0.0.0 /Users/riccardoforina/Code/insights-chrome
├─┬ @data-driven-forms/pf4-component-mapper@3.12.0
│ ├── @patternfly/react-core@4.168.8 deduped
│ └── @patternfly/react-icons@4.19.8 deduped
├── @patternfly/patternfly@4.151.4
├─┬ @patternfly/quickstarts@1.2.0-rc.1
│ ├─┬ @patternfly/react-catalog-view-extension@4.12.15
│ │ ├── @patternfly/patternfly@4.122.2
│ │ └── @patternfly/react-core@4.168.8 deduped
│ └── @patternfly/react-core@4.168.8 deduped
├─┬ @patternfly/react-core@4.168.8
│ ├── @patternfly/react-icons@4.19.8 deduped
│ └── @patternfly/react-tokens@4.20.8 deduped
├── @patternfly/react-icons@4.19.8
├─┬ @patternfly/react-table@4.37.8
│ ├── @patternfly/react-core@4.168.8 deduped
│ ├── @patternfly/react-icons@4.19.8 deduped
│ └── @patternfly/react-tokens@4.20.8 deduped
├── @patternfly/react-tokens@4.20.8
├─┬ @redhat-cloud-services/frontend-components-notifications@3.2.4
│ ├── @patternfly/react-core@4.168.8 deduped
│ └── @patternfly/react-icons@4.19.8 deduped
├─┬ @redhat-cloud-services/frontend-components-pdf-generator@2.6.7
│ ├─┬ @patternfly/react-charts@6.15.20
│ │ └── @patternfly/react-tokens@4.20.8 deduped
│ ├── @patternfly/react-core@4.168.8 deduped
│ ├── @patternfly/react-icons@3.15.17
│ └── @patternfly/react-tokens@4.20.8 deduped
├─┬ @redhat-cloud-services/frontend-components-utilities@3.2.4
│ ├── @patternfly/react-core@4.168.8 deduped
│ └── @patternfly/react-table@4.37.8 deduped
└─┬ @redhat-cloud-services/frontend-components@3.5.0
  ├── @patternfly/react-core@4.168.8 deduped
  ├── @patternfly/react-icons@4.19.8 deduped
  └── @patternfly/react-table@4.37.8 deduped
```

@patternfly/react-core is on version 4.168.8m which is [two months old](https://www.npmjs.com/package/@patternfly/react-core/v/4.168.8).

Can we use an updated version in our app so to get some bug fixes we require? 
What about the CSS file, I suppose we can't load it in our federated module to avoid messing with the chrome app. Is this correct?

What other options do we have?

**Comment by Hyperkid123** [comment]
@riccardo-forina the strategy si to keep up the latest version which does not introduce any bugs. However, from 2022 we will regularly update PF dependencies to the latest stable version.

> Can we use an updated version in our app so to get some bug fixes we require?

Yes, but it would be better to update chrome. In fack, @radekkaluzik opened a PF update PR today: https://github.com/RedHatInsights/insights-chrome/pull/1720.

**Comment by riccardo-forina** [comment]
Oh ok so the version of PF isn't tied to a release cycle or anything, it can be updated at any time? That's good to know.

So I have more info to report, how long does it take for a merged PR to go live on the different environments?

**Comment by Hyperkid123** [comment]
stage beta will be in a couple of minutes and we actually plan to update prod-stable to the latest version later today. I am just waiting for an ack from one of the teams.

**Comment by riccardo-forina** [comment]
Cool, thanks a lot :)
