### ISSUE TITLE
OpenShift on cloud: details navigation link

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#182]
Cost Management needs a new navigation link, named 'OpenShift on cloud details'. The link should route to insights/platform/cost-management/ocp-on-aws.

Please also rename the 'OpenShift details' and 'AWS details' links as  'OpenShift details' and 'Cloud details' -- all sentence case. 

FYI, we need to rename 'AWS' as 'Cloud' for summit demos.

**Comment by dlabrecq** [comment]
Can someone please add this navigation link change for Cost Management?

**Comment by iphands** [comment]
Sure. We are right in the middle of the re-arch for the new hostname.
Should be an easy addition though. We can add it to the backlog and pick it up after we move everything around this sprint.

**Comment by chargio** [comment]
We really need this for testing before Summit. Can we speed this up?

**Comment by iphands** [comment]
> Cost Management needs a new navigation link, named 'OpenShift on cloud details'. The link should route to insights/platform/cost-management/ocp-on-aws.

You say this ^ then this:
> FYI, we need to rename 'AWS' as 'Cloud' for summit demos.

@chargio @dlabrecq  do we really want the /cost-management/ocp-on-aws link? i.e. bake aws in there?

**Comment by dlabrecq** [comment]
We're not concerned with 'aws' in the URL, just the English names appearing in the navigation pane.

To recap, there will be three links under Cost Management.

- 'OpenShift Details' needs to be renamed as 'OpenShift details' 
- 'AWS Details' needs to be renamed as 'Cloud details'
- 'OpenShift on AWS Details' has not been created 

The 'OpenShift on AWS Details' link is needed ASAP so QE can begin testing for summit.

**Comment by iphands** [comment]
This is changed already in CI
Please verify

**Comment by dlabrecq** [comment]
If it's not too much trouble, 'OpenShift on cloud details' should be the first link. Thank you!

**Comment by iphands** [comment]
So it should be:
- OpenShift on cloud details
- Overview
- OpenShift details
- Cloud details

?? this seems way off to me.
define:first

**Comment by dlabrecq** [comment]
Sorry, I meant it should be the first details link. To clarify, we would like the links to appear in this order.

- Overview
- OpenShift on cloud details
- OpenShift details
- Cloud details

**Comment by iphands** [comment]
Cool, should land in a few mins.
Closing, please re-open if there is some issue.

**Comment by iphands** [comment]
Oh wait.. we still NeedsProd.
Will do the prod proxy magic once you give the thumbs up that CI QA look as expected.
@dlabrecq  please lemme know if the pre prod setup looks right

**Comment by ryelo** [comment]
Closing due to staleness, if you have another issue with nav, please open it in cloud-services-config
