### ISSUE TITLE
getOfflineToken fails if there is a URL param

### ISSUE THREAD

**Issue by jschuler** [RedHatInsights/insights-chrome#1838]
Example:
1. Go to https://console.redhat.com/openshift/token/show?test=true, notice the **?test=true** at the end
1. We call `insights.chrome.auth.getOfflineToken()` which first returns an expected error of `not available`, so we will call `insights.chrome.auth.doOffline();` which reloads browser.
1. Get an error instead of token:

I see in network console:
```
Request URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
Request Method: POST
Status Code: 400 Bad Request

error: "invalid_grant"
error_description: "Incorrect redirect_uri"
```

If there is no extra URL param this works fine.

**Comment by Hyperkid123** [comment]
Well, I think might be an SSO issue.

We are sending a `noauth` query param with a hash. I just think the SSO does not expect any other query parameters so it just simply does not accept the redirect link with additional query parameters. It does not even accept hash in the `redirectUri` param.

@ryelo can we talk to SSO dev team about why not parameters are permitted?

**Comment by ryelo** [comment]
Yep I can send them a message to ask why we can't add additional params. My assumption is that we _could_, but we just have to put a blob in their config to allow it.

**Comment by kdoberst** [comment]
@Hyperkid123 @ryelo This issue is making development on the ROSA wizard more difficult - wondering where the conversation with the SSO team is at.

**Comment by jschuler** [comment]
This will also have an impact on other things that add URL params, like quick starts

**Comment by alechenninger** [comment]
Can someone paste the *exact* request that is being made to SSO?

Is the additional query parameter a part of the redirect URI? If so, this is not allowed, per https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2

To send variable state along with a redirect, you must use the `state` parameter.

**Comment by jschuler** [comment]
Here's an example of what I am observing at the moment:
- Navigate to `https://console.redhat.com/openshift/token/show?test=true`
- I see in the Network log:
```
Request URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
Request Method: POST
Status Code: 400 
```
Payload:
```
code: 93ee20be-e714-46cc-93b1-d9b18362c6ad.1afcace9-6923-474b-8a2a-8f384876191f.78d5cce2-4b4b-419e-9007-28deefc1edaf
grant_type: authorization_code
client_id: cloud-services
redirect_uri: https://console.redhat.com/openshift/token/show?noauth=2402500adeacc30eb5c5a8a5e2e0ec1f
```
Response:
```
{"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
```

**Comment by Hyperkid123** [comment]
as @alechenninger we will probably have to move the quickstart to the `#state` hash in the URL to get around the error. Essentially that will force use to sanitize the URL and the append the quickstart query param back once we are authenticated

**Comment by d-ramakri** [comment]
How involved / complicated is the change @alechenninger @ryelo and who would do it?  Sorry to pull the 'urgent' card - this issue is directly linked to a high priority / high visibility complaint from customers on the ROSA day 1 wizard for OCM

**Comment by Hyperkid123** [comment]
@d-ramakri @jschuler  OK, I have opened a PR with a path **BUT**, if @alechenninger says we should use the CLI auth then I would strongly recommend doing so and deprecating the `doOffline` and `getOfflineToken` functions. And eventually getting rid of them.

I assume that somewhere in your UI/QuickStart there is a guide involving getting the token and then pasting a command including the token somewhere in the user's terminal right? Is it possible to change the guides to include the CLIT auth?

**Comment by jschuler** [comment]
Thanks @Hyperkid123 ! And yes I agree it would be wonderful to get rid of the clunky copying of token into the CLI step altogether, that would be preferable. I hope we can go down that path, but in the meantime thank you for the fix!
