### ISSUE TITLE
Analytics: isProd check includes local dev env URL

### ISSUE THREAD

**Issue by jschuler** [RedHatInsights/insights-chrome#1972]
When we launch our local dev env at `prod.foo.redhat.com` and send analytics track events, it uses the prod write key
https://github.com/RedHatInsights/insights-chrome/blob/883f5ce806dc8f8de5fade7f7ba255fff0a09e04/src/js/utils.ts#L143

I would expect to use the dev write key from a local dev env.

**Comment by jschuler** [comment]
In HAC OCM that process has been for us to use a prod SSO account. I am not sure yet what it will take to use stage SSO account and get it hooked up with the right entitlements.
Would it be possible to add an additional check when sending data to analytics, i.e. `prod.foo.redhat.com` && a URL param like `env=production` or a localStorage flag?

**Comment by cben** [comment]
I'd suggest insights-chrome should not parse URL params, to not conflict with apps' use of params (OCM itself already has an `?env=...` param with a different meaning).  

But if you could add an option to override analytics env somewhere in insights-chrome API, OCM code could call it. 🙏

**Comment by Hyperkid123** [comment]
> Would it be possible to add an additional check when sending data to analytics, i.e. prod.foo.redhat.com && a URL param like env=production or a localStorage flag?

As @cben said, we can't just start messing around with URL params. But you can define your own env param and decide on that. We can't change the isProd return value as it would introduce regressions to the rest of the apps (about 40) on the platform.

**Comment by jschuler** [comment]
Yes I understand, it would be nice to have more control here as to which key is picked:
https://github.com/RedHatInsights/insights-chrome/blob/9f574258bbd46a9ef2b1f43aa48ae0bad83a472c/src/js/App/analytics/segment-analytics.tsx#L149

It could be possible to either add a check there, or modify the isProd method in a way that would not introduce regressions, like:
```
 return location.host === 'cloud.redhat.com' || location.host === 'console.redhat.com' || (location.host.includes('prod.foo.redhat.com') && !(localStorage.getItem('chrome:analytics:dev') === 'true')); 

```

**Comment by Hyperkid123** [comment]
Yeah sure that is something we can add.
