### ISSUE TITLE
Navigation pane does not highlight properly

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#222]
The Insights navigation pane does to highlight properly when navigating between pages. For example, the user can jump from the Cost Management's overview page via a link to the OpenShift details page. Is there something the Cost Management UI needs to do in order for Insights to understand which route the user has jumped to?

**Comment by iphands** [comment]
Yeah there is some code that an app has to do to tell chrome which subnav item is currectly "active".
@dlabrecq this is what you are asking about right?

@karelhala whats the best example/doc we have of this?

**Comment by karelhala** [comment]
@dlabrecq I checked current UI and can't reproduce your error. When I navigate to `/hybrid/catalog/portfolios` and change url to `/hybrid/cost-management/ocp?group_by[project]=*&order_by[cost]=desc` correct item in navigation is selected and highlighted.

![Peek 2019-04-08 17-51](https://user-images.githubusercontent.com/3439771/55738223-f825e180-5a26-11e9-911d-78ff25dc87e5.gif)

**Comment by dlabrecq** [comment]
When in the overview page, click on the "All Projects" link. The URL in the browser changes to https://ci.foo.redhat.com:1337/hybrid/cost-management/ocp?order_by[cost]=desc; however, the "Overview" navigation link is still highlighted. 

![chrome-capture](https://user-images.githubusercontent.com/17481322/55741244-d0208900-59fa-11e9-8b2a-00f58a431701.gif)

**Comment by karelhala** [comment]
Oh I see thanks for clearing it up. So you want to perform in app redirect that activates app in navigation. I don't think there's an action to that, but we will add it to allow such thing.

**Comment by dlabrecq** [comment]
When I call `insights.chrome.appNavClick({id: 'ocp-on-aws'})`, the navigation pane collapses. I cannot see if the selection was made.

![chrome-capture](https://user-images.githubusercontent.com/17481322/56585806-8f08a700-65ac-11e9-9a13-a97c246fe1b6.gif)

**Comment by karelhala** [comment]
Thanks for pointing this out, the initial fix was only for first level navs and I did not checked with secondary level navigation, PR https://github.com/RedHatInsights/insights-chrome/pull/262 fixes this issue, so calling `insights.chrome.appNavClick({id: 'ocp-on-aws', secondaryNav: true})` will highlight correct item in nav.

**Comment by dlabrecq** [comment]
@karelhala I tried a couple approaches -- also wrapped with a timeout. I see my break points being hit, but neither approach seems to work. Is there something else I should try?

Using onClick:
![Screen Shot 2019-04-23 at 1 37 23 PM](https://user-images.githubusercontent.com/17481322/56603215-457c8400-65cd-11e9-863f-3f24dde58ef4.png)

Using the page's componentDidMount:
![Screen Shot 2019-04-23 at 1 37 14 PM](https://user-images.githubusercontent.com/17481322/56603245-5a591780-65cd-11e9-8331-6b0d8c6ffafb.png)

**Comment by dlabrecq** [comment]
Ah, I see that hasn't been merged yet.
