### ISSUE TITLE
Do not show JWT verification error

### ISSUE THREAD

**Issue by dkuc** [RedHatInsights/insights-chrome#243]
Either redirect me to sign on, or say that I'm not currently logged in the upper right.
![Screenshot from 2019-04-09 11-29-30](https://user-images.githubusercontent.com/9499094/55813665-25bc6a80-5abb-11e9-982e-01d9d7a86f56.png)

**Comment by iphands** [comment]
FYI this is an API error surfaced in the frontend.
We have big stories leading up to Summit to bullet proof a lot of JWT client side impl... so this should be closed when that is done.
