### ISSUE TITLE
Getting a 403 on https://console.redhat.com/openshift/overview/rosa/hands-on/

### ISSUE THREAD

**Issue by jschuler** [RedHatInsights/insights-chrome#2811]
The following was reported 
> Getting a 403 on https://console.redhat.com/openshift/overview/rosa/hands-on/

<img width="1473" alt="Screenshot 2024-04-09 at 2 32 41 PM" src="https://github.com/RedHatInsights/insights-chrome/assets/869106/62a1ce5f-d61c-4fa7-b4c9-4be4c83ec0e0">

Looks like we need to relax [AUTH_ALLOWED_ORIGINS](https://github.com/RedHatInsights/insights-chrome/blob/1589b70527fd4d49ed49420bf7c5db5c4387e1f8/src/utils/iqeEnablement.ts#L15) to add auth headers to these?:

```
api.demo-experience.stage.demo.redhat.com
api.demo-experience.demo.redhat.com
```

@cben @Hyperkid123 @aneelac22

**Comment by ryelo** [comment]
Can you please open a Jira ticket in RHCLOUD for this too?

**Comment by jschuler** [comment]
@ryelo https://issues.redhat.com/browse/RHCLOUD-31940

**Comment by jschuler** [comment]
Verified fixed
