### ISSUE TITLE
Update the Subscription Watch link for Documentation

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/insights-chrome#490]
## Description
Update the `Documentation` link to the left nav for Subscription Watch. 

## Notes
- Updated documentation location per CCS, link should point towards
   - https://access.redhat.com/documentation/Subscription_Central

## Related issues
- #472 
- https://github.com/RedHatInsights/curiosity-frontend/issues/129

 @jeperry @bclarhk @jlprevatt

**Comment by rblackbu** [comment]
This is link correct as provided by David Voss on 12/04/19 in the subscriptions Slack channel.

**Comment by cdcabrera** [comment]
Prod push happened, we've updated the reference towards
`https://access.redhat.com/documentation/Subscription_Central/`

**Comment by rblackbu** [comment]
+1 to verifying the link as showing active
