### ISSUE TITLE
Unable to logout of UI

### ISSUE THREAD

**Issue by lcouzens** [RedHatInsights/insights-chrome#63]
Description 
After login you are unable to log out again using username -> logout

To Reproduce

1. Go to CI environment dashboard
2. Login to UI
3. Click on username
4. Try to click 'logout'

Expected behavior
User should get logged out.

Screenshots
![screenshot from 2018-11-07 10-29-09](https://user-images.githubusercontent.com/18352403/48145702-50578c80-e2ab-11e8-8e39-5cd95f903c4e.png)

Desktop (please complete the following information):
OS: fedora
Browser firefox
Version 63

**Comment by ryelo** [comment]
@lcouzens Thanks! This should be updated when #59 is merged!

**Comment by karelhala** [comment]
This is no longer an issue, am I right?

**Comment by lcouzens** [comment]
@karelhala Right this is working correctly for me now so can probably be closed. :+1:
