### ISSUE TITLE
Show navigation links dynamically

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#65]
As a Cost Management user, I do not want to see the OCP and AWS links in the Insights navigation pane when AWS & OCP providers are not available. We would like the ability to show links dynamically.

See https://github.com/project-koku/koku-ui/issues/198 for additional details.

**Comment by karelhala** [comment]
Thanks for the issue, we are currently supporting static navigation. If you want to have it dynamically changed (based on user's data) we need endpoint to call and let you to decide which URLs you want to display.

**Comment by iphands** [comment]
I think we closed this per a discussion with the leads, please re open if this is something needed before summit
