### ISSUE TITLE
Page refresh appears to be broken

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#66]
Refreshing the Cost Details page of Cost Management ends up displaying a blank page. I have to enter the following URL to start over. This only started happening after integrating with the Insights platform.

https://prod.foo.redhat.com:1337/insights/platform/cost-management/

See https://github.com/project-koku/koku-ui/issues/175 for additional details

**Comment by karelhala** [comment]
There is a problem in `project-koku` you are starting `/` in [index.tsx#L11](https://github.com/project-koku/koku-ui/blob/master/src/index.tsx#L11) and once you are navigated somewhere and hit `F5` router is confused and doesn't know from where to serve content and is lost.

When I tried it I bumped into couple more problems, but that might be related solely to my machine.

**Comment by dlabrecq** [comment]
It appears that only `process.env.APP_PUBLIC_PATH` is being used, not the default `insights/platform/cost-management` path.

**Comment by dlabrecq** [comment]
Closing as Insights beta seems to be refreshing as expected.
