### ISSUE TITLE
Provide all PatternFly utilities and layouts

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#67]
It appears that the Insights chrome does not provide all pf-next utilities and layouts. Specifically, the `.pf-l-split` layout and `.pf-u-display-*` utilities.

It's possible Insights may selectively include individual utilities and layouts? However, providing all utilities and layouts would allow us to remove all of the custom CSS for the Cost management overview page.

See https://github.com/project-koku/koku-ui/issues/271 for additional details.

**Comment by ryelo** [comment]
As of now, we're only using the layouts and utilities to actually render the chrome. Each app is consuming Patternfly 4 React and using the grid, split, etc. to lay out their pages.

**Comment by ryelo** [comment]
I'm not really sure why you cannot include PF4. 

Here's an example of importing Patternfly and using a split inside of the starter app - which consumes the chrome styles.

Repo:
https://github.com/RedHatInsights/insights-frontend-starter-app/tree/examples/pf-split

Page:
https://github.com/RedHatInsights/insights-frontend-starter-app/blob/examples/pf-split/src/SmartComponents/SamplePage/SamplePage.js

Styles:
https://github.com/RedHatInsights/insights-frontend-starter-app/blob/examples/pf-split/src/SmartComponents/SamplePage/sample-page.scss

**Comment by dlabrecq** [comment]
More specifically, we're looking to use these utilities with the Cost Management overview header.

`<header className="pf-u-display-flex pf-u-justify-content-space-between pf-u-align-items-center">`

We're able to include @patternfly/patternfly-next/utilities/Display/display.css and @patternfly/patternfly-next/utilities/Flex/flex.css' ourselves, so I'll close this issue. 

Ideally, Insights would make these PF4 utilities available for all apps to use.

**Comment by karelhala** [comment]
@dlabrecq that is interesting idea to privde basic PF4 utilities, but I don't think it's OK for us to force all the apps to use one version of PF4 dep. Imagine that one app is using outdated PF4 and with new version all variables gets a prefix or whatever and the app is blown up and broken without the authors of such app doing anything. So importing PF4 in each app is much better and maintanable for both parties insights platform and insights apps

**Comment by dlabrecq** [comment]
Insights is already forcing Cost Management to use a specific version of PF4. I'm thinking quite the opposite. Potentially, we could include utilities from a version of PF4 different than what Insights is using? It will be tough keeping that in sync; thus, the ask to also include the PF4 utilities/layouts to ensure the same version.

**Comment by ryelo** [comment]
We're not forcing apps to use a specific version of PF4. The starter app is currently using `1.0.41` , chrome is using `1.0.62`, and Advisor is using `1.0.68`. Your app should take precedence when rendering because of the ESI tags.

Additionally, you could always write the css for this example because it doesn't rely on any variables.

We're also working on custom layouts that should resolve the first and second `pf-l-page__main-section`
