### ISSUE TITLE
Is it feasible to vendor Pendo JS instead of loading directly from 3rd party?

### ISSUE THREAD

**Issue by cben** [RedHatInsights/insights-chrome#674]
Hi, I see the Pendo "agent" javascript is loaded directly from `https://cdn.pendo.io/agent/static/${API_KEY}/pendo.js`.
Loading JS directly from 3rd party domains is IMO suboptimal for security:
1. If their domain / certificates / cdn are somehow compromised by another attacker, they can serve malicious code to our users with no trace of it left to audit later.
2. We have no way of knowing whether the same JS is served to all users.
  If somebody in Pendo goes evil and attacks our users, again, no trace left.
3. We do not control upgrades, have no process for auditing their code.

A better practice for proprietary analytics would be to vendor some frozen version of their code, and update it manually.
Does Pendo offer a non-obfuscated version of their client JS at all?  Has anyone ever looked at what it does / sends?  Even if we don't review their code before using, having it publicly available and open for _potential future audit_ would be better than nothing...

[Off-topic: in an ideal world, we'd use open-source analytics, hosting user data ourselves.]

https://www.pendo.io/data-privacy-security/ has this to say about their CDN:
> The JavaScript code is hosted and deployed in Amazon’s Cloudfront Content Distribution Network (CDN)

1. Well to be realistic, if anyone compromises Cloudfront, half the world is pwned :-)
2. Does Cloudfront guarantee same response for same URL to all users (which in our case is all cloud.redhat.com users)?  That could make a narrowly targetted attack harder.  But it doesn't  exactly, depends on `Vary` header etc...  Also if they push an evil version for a short time, then replace it, nobody would notice.

To be clear, I'm not talking about our business relationship with Pendo, and whether [their promises](https://support.pendo.io/hc/en-us/articles/360031862372-Security-and-Privacy) are *legally* sufficient.  Merely about the *technical* ability to inspect their code & control when it changes.

Briefly looking at pendo docs e.g. https://developers.pendo.io/docs/?bash#installation, there is little mention of alternatives to the "snippet" loading JS from the CDN :frowning: 
However https://support.pendo.io/hc/en-us/articles/360022819711-Snippet-Install#InstallFAQ says :smile: :

> ### Can I Host The Agent Locally?
> The installation snippet pulls in pendo.js which contains the Pendo agent code. pendo.js can be downloaded and hosted via your application if you do not want it to be pulled from Pendo’s CDN. Admins can download this code on the Subscription Settings page by clicking on the desired Web App, clicking the "Agent Settings" tab, clicking on "Manage Staging/Prouction Settings" and then by clicking the "Download" link under your currently selected "Guide Delivery Settings". Note that you will need to update this reference in the installation snippet to point to your hosted pendo.js file.

**Comment by cben** [comment]
It seems previously Pendo had some github/npm packages, e.g. https://github.com/pendo-io/ng-pendo, but (1) now says "This is no longer the correct way to install Pendo into your application." (2) it was equivalent to just the "snippet", it still loads the main JS from cdn.pendo.io

- https://github.com/pendo-io/analytics.js-integration-pendo/ is maybe more open ?  no idea.

**Comment by Hyperkid123** [comment]
@cben I am closing this one. Pendo is now loaded through the segment.io
