### ISSUE TITLE
Normal UI shouldn't be available when logged in user has no valid Red Hat account

### ISSUE THREAD

**Issue by bsquizz** [RedHatInsights/insights-chrome#69]
If you log in to the platform UI via SSO with a user that has no Red Hat account number associated with their user ID, the UI still "works" but all the backend queries fail because 3scale does not pass the `account_number` in the `x-rh-identity` header.

If a user logs in who does not have a valid account number, we should display some kind of error page.

**Comment by iphands** [comment]
/agreed but I would like to see the UXD + BU folks take on the "what shoud a user see" part of this... Its rather easy for us to -in chrome- force display some page for users in this state.

**Comment by ryelo** [comment]
I think this has been solved by the unauthenticated landing page.
