### ISSUE TITLE
"About page" has a transparent background and is hard to read

### ISSUE THREAD

**Issue by theute** [RedHatInsights/insights-chrome#697]
In CI:
![image](https://user-images.githubusercontent.com/311855/77052220-cbb36d00-69cc-11ea-8186-babaace39d30.png)
(Works on on prod)

**Comment by ryelo** [comment]
Hi, this is working on some pages correctly and others not so much. You can see, on the ci-beta landing page, for example, the modal looks fine. I'll investigate this more. I'm assuming it's some kind of style mixup somewhere.
