### ISSUE TITLE
Navigation bar doesn't render correctly when a element id is the same as a subitem id

### ISSUE THREAD

**Issue by josejulio** [RedHatInsights/insights-chrome#710]
This is how it looks when going to `insights/policies`

![Screenshot_2020-03-25_09-25-38](https://user-images.githubusercontent.com/3845764/77583811-500f5f80-6ea7-11ea-9825-f994f5ccce1d.png)

And this is `insights/compliance/policies`

![Screenshot_2020-03-25_14-47-57](https://user-images.githubusercontent.com/3845764/77583991-a381ad80-6ea7-11ea-89f5-5944714c6cf7.png)

**Comment by karelhala** [comment]
This is being tracked in JIRA https://projects.engineering.redhat.com/browse/RHCLOUD-5432 and we'll get to it this sprint.

**Comment by josejulio** [comment]
Thanks! Feel free to close this one if not needed.

**Comment by ryelo** [comment]
Closing because it's fixed 😄
