### ISSUE TITLE
Buttons on chroming do not work

### ISSUE THREAD

**Issue by chargio** [RedHatInsights/insights-chrome#75]
**Describe the bug**
The buttons on the chroming do not work

**To Reproduce**
Always

**Expected behavior**
They work

**Screenshots**
![image](https://user-images.githubusercontent.com/7500590/49286807-90212680-f49b-11e8-9c0d-ef381cfbb741.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version latest

**Additional context**

**Comment by ryelo** [comment]
Currently, these buttons are just placeholders and don't have any values. When we finalize what buttons we want and what they do, we'll add content in them.
