### ISSUE TITLE
Problem with Inisghts & onClick events

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#80]
I'm encountering an issue with Inisghts and onClick events. 

1. Navigate to the "Cloud Cost" page of Cost Management
2. Choose the "Group By" menu -- this is a PF4 dropdown
3. Choose the "Sort By" menu in the toolbar -- this is a PF3 Sort.TypeSelector
4. Insights renders a blank page

In order to fix the issue with the PF4 dropdown, I was able to add event.preventDefault(), like so: 

```
  <Dropdown
    onClick={event => event.preventDefault()} <<<
    dropdownItems={groupByOptions.map(option => (
      <DropdownItem
        onClick={event =>
          this.handleGroupByItemClick(event, option.value)
        }
      >
    ...
```
I have not found a workaround for the PF3 Sort.TypeSelector component.

The error in the browser console is:
![screen shot 2018-12-06 at 12 06 41 pm](https://user-images.githubusercontent.com/17481322/49600108-6ca12480-f950-11e8-831a-975d9f8dac38.png)

**Comment by dlabrecq** [comment]
I've replaced the PF3 Sort.TypeSelector in the toolbar with a PF4 dropdown, but feel like the event.preventDefault() code is a workaround and shouldn't be necessary.

Is Insights listening for onClick events? Could this be a patternfly-react issue (it was working prior to integrating with Insights)?

**Comment by karelhala** [comment]
insights is not listening for `onClick` events, at least not to my knowledge, but I'd bet that PF3 dropdown which is using bootstrap was somewhat comfused and broken. I'd adwise not to use PF3 components since they don't play well with rest of the app.

**Comment by dlabrecq** [comment]
That's a PF4 dropdown.

**Comment by dlabrecq** [comment]
Perhaps Insights isn't listening specifically to `onClick`, but the chrome appears to be interfering somehow. Suggesting not to use PF3 isn't an option.

**Comment by dlabrecq** [comment]
I can still reproduce it. There is also `event.preventDefault();` on line 97 of detailsToolbar.tsx. Simply make a selection from the `Group By` dropdown.

I don't believe it's a PatternFly issue because it's a simple onClick that I added myself. If I stop the propagation, then Insights doesn't attempt to navigate away from the current page.

**Comment by karelhala** [comment]
Looking at the generated code by `Toolbar` component from PF3 it creates form and dropdown creates button without any specified type which by default tries to submit such form [1]. I guess we can close this issue since it's not insights specific and open new one in PF4 (both design and react implementation) with `<button type="button" ... >`

[1] https://stackoverflow.com/questions/9824808/disable-form-auto-submit-on-button-click
