### ISSUE TITLE
Navigation links not enabled properly

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#83]
There is an "All Services" link on the Cost Management dashboard. This takes the user directly to the Cloud Cost page. However, the link in the Insights navigation pane is not activated. Instead, the "Overview" link remains active.

Is there an Insights API that we should be using when navigating to other pages?

![screen shot 2018-12-07 at 12 06 00 pm](https://user-images.githubusercontent.com/17481322/49661953-902fa200-fa18-11e8-81cc-e163499baadd.png)

**Comment by karelhala** [comment]
Oh, great catch. We forgot to expose such function, but I am working on PR that fixes such thing and you're gonna call `window.insights.chrome.appNavClick({id: 'some-id'})` where `id` is either ['', 'aws', 'ocp']
