### ISSUE TITLE
Multiple window/tabs issue

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#84]
While testing Cost Management, in an existing browser window, I opened a new incognito window using a similar URL. Then, I clicked on the navigation pane, under Cost Management. This unexpectedly controls both windows and/or tabs.

Not only does this happen on both Chrome and Firefox, but I was able to use the Firefox window to control Chrome.

Below is a recording of a Firefox (private) window controlling two other windows; Firefox and Chrome.
![3windows](https://user-images.githubusercontent.com/17481322/49758362-bd848600-fc8c-11e8-8d0e-1fcadc7f7250.gif)

I suspect this is related to running a local proxy, so feel free to close if this is not considered an issue?

**Comment by iphands** [comment]
This is very intentional behavior. Its provided by browsersync and its an active thing.
If you want some way to disable it, I'd be happy to look into that... but its certainly not a bug.
