### ISSUE TITLE
Sidebar drop-down "Migration Services" becomes "Migration"

### ISSUE THREAD

**Issue by carlosthe19916** [RedHatInsights/insights-chrome#868]
When I access to Migration Analytics I can see a drop-down in the left sidebar of the page; when I select the option "Migration Services" it navigates to "Migration Analytics" but the value of the dropdown becomes "Migration" rather than "Migration Services". See the gift attached.

Is this a bug or it is the expected behavior?

![Peek 2020-07-10 12-27](https://user-images.githubusercontent.com/2582866/87146988-1c1c4680-c2ac-11ea-9b96-659e67f29618.gif)

**Comment by ryelo** [comment]
This is generated from the title given inside of https://github.com/RedHatInsights/cloud-services-config/blob/476ad453709d4a0477db190e443fee4a67d67585/main.yml#L323

**Comment by ryelo** [comment]
Going to close this issue in chrome because if you would like it to change, a PR should be opened in cloud services config.
