### ISSUE TITLE
Change buttons in header to links

### ISSUE THREAD

**Issue by rvsia** [RedHatInsights/insights-chrome#891]
**Description**

Is it possible to change these buttons in header to links? I think it would make the site more accessible and also it would allow to use middle mouse button to open the link in the new tab. 

**Settings**
- https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/App/Header/Tools.js#L31

**Api documentation**
- https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/App/Header/Tools.js#L50

**Comment by rvsia** [comment]
cc @karelhala

**Comment by karelhala** [comment]
Good point, I'll create JIRA issue to track this.

**Comment by rvsia** [comment]
@karelhala thank you!
