### ISSUE TITLE
PatternFly's GridItem color is overridden as white text

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-chrome#92]
Insights appears to be overriding the `GridItem` component of @patternfly/react-core. 

I've added a bullet chart to the OCP details page for Cost Management, but all the text (labels, legend, etc.) is white. Looking at the HTML elements output by `GridItem`, I can confirm that `chrome.css` is setting the color to white.

Before:
![before](https://user-images.githubusercontent.com/17481322/50291147-bce1b180-043b-11e9-92de-caffedd9d071.png)

When I deactivate the color style, I can see the text in my bullet chart. Also, if I don't place the chart in the `GridItem`, I can see the text.

After:
![after](https://user-images.githubusercontent.com/17481322/50291212-f3b7c780-043b-11e9-99e9-eff59935e394.png)

My workaround is to set the color manually, but prefer not to do that.

**Comment by karelhala** [comment]
This comes from `pattenfly-base` sadly we don't have any control over this :cry: If you notice the styling rule you can see that it targets any `.pf-*::after` elements.

**Comment by dlabrecq** [comment]
Layouts are not included in patternfly-base. In fact, there are no color properties specified for grid.scss in patternfly-core.
