### ISSUE TITLE
Navigation sidebar label has changed

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-chrome#95]
Before it had label `Insights Global Navigation`, now it has `Primary Nav Mixed Example`. I don't see a reason to change to that name.
https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/App/Sidenav/Navigation.js#L41
@karelhala

**Comment by karelhala** [comment]
@quarckster good catch! I'll change it to original.
